name: Library Python Tests

# Run when code is pushed to main,
# when a pull request is created,
# or when manually started
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # Downloads the repository onto the runner
      - name: Checkout repository
        uses: actions/checkout@v7

      # Prints my name
      - name: Print my name
        run: echo "Hello, Joe!"

      # Installs Python
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      # Installs the modules from requirements.txt
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      # Runs the pytest tests
      - name: Run pytest tests
        run: python -m pytest testing/testing_module.py -v

      # Runs the unittest tests
      - name: Run unittest tests
        run: python -m testing.unittest_module -v