# This is a basic workflow to help you get started with Actions

name: joes Job

# Controls when the workflow will run
on:
  # Runs when code is pushed to main
  push:
    branches: ["main"]

  # Runs when a pull request targets main
  pull_request:
    branches: ["main"]

  # Allows the workflow to be run manually
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Use a GitHub-hosted Linux machine
    runs-on: ubuntu-latest

    steps:
      # Download the repository onto the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run a basic command
      - name: Run a one-line script
        run: echo "Hello, Joe!"
